### ISSUE TITLE
Change docs theme

### ISSUE THREAD

**Issue by a-recknagel** [a-recknagel/stenotype#12]
I initially picked the flask theme because I like the minimal look, but there is other good ones out there. The [`sphinx_rtd_theme`](https://sphinx-rtd-theme.readthedocs.io/en/stable/) in particular is worth a look since we ~~want to include~~ have included text boxes that happen to look very read-the-docs-y (alternatives include changing the tab-box css to look more flasky or accepting the visual discrepancy).

- [x] wait a little to see if people care about this topic
- [x] decide which theme to pick. default choice: `sphinx_rtd_theme`

**Comment by maxfischer2781** [comment]
+1 on ``sphinx_rtd_theme`` -- IMO it is well suited for technical documentation.
